name: Unzip File

on: 
  push:
    paths:
      - '*.zip'  # Trigger the workflow on a push that includes a .zip file

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unzip file
        run: unzip *.zip -d unzipped_files/

      - name: Commit unzipped files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add unzipped_files/
          git commit -m "Unzipped files"
          git push
